# Generated by Django 5.1.6 on 2025-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
